"""added url column in books table

Revision ID: 5eb0ceaa3869
Revises: 939dcec95c5f
Create Date: 2026-10-08 16:52:39.542379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb0ceaa3869'
down_revision: Union[str, Sequence[str], None] = '939dcec95c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_url')
    # ### end Alembic commands ###
