"""updated the book table and added 2 new columns

Revision ID: 7e88f03d1046
Revises: e94d8c0cbd5d
Create Date: 2026-09-29 18:54:51.738748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e88f03d1046'
down_revision: Union[str, Sequence[str], None] = 'e94d8c0cbd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('books', sa.Column('reviews', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_column('books', 'reviews')
    op.drop_column('books', 'genres')
    # ### end Alembic commands ###
