"""created 2 more tables: recomended and shelf books tables

Revision ID: e94d8c0cbd5d
Revises: 131ff75030a6
Create Date: 2026-09-29 17:59:22.464768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94d8c0cbd5d'
down_revision: Union[str, Sequence[str], None] = '131ff75030a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('book_url', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_books_id'), 'shelf_books', ['id'], unique=False)
    op.create_table('recommended_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('book_url', sa.String(), nullable=True),
    sa.Column('shelf_book_attached_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shelf_book_attached_to'], ['shelf_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_books_id'), 'recommended_books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommended_books_id'), table_name='recommended_books')
    op.drop_table('recommended_books')
    op.drop_index(op.f('ix_shelf_books_id'), table_name='shelf_books')
    op.drop_table('shelf_books')
    # ### end Alembic commands ###
